export enum ModuleNotification {
  RETRIEVE = "GET_GOOGLE_TASKS",
  CONFIG = "CONFIGURE_GOOGLE_TASKS",
  RESULTS = "GOOGLE_TASKS_RESULT",
  ERROR = "GOOGLE_TASKS_RETRIEVE_ERROR",
  COMPLETE = "GOOGLE_TASKS_COMPLETE",
  COMPLETERESULT = "GOOGLE_TASKS_COMPLETE_RESULT",
  UNCOMPLETERESULT = "GOOGLE_TASKS_UNCOMPLETE_RESULT"
}
